name: Votify
version: 1.0.0
main: org.mapplestudio.votify.Votify
api-version: 1.16
author: ImJopeh
description: A professional voter reward plugin.
softdepend: [Votifier, PlaceholderAPI]

commands:
  votify:
    description: Main command for Votify.
    aliases: [vote, v]
  votifyadmin:
    description: Admin command for Votify.
    permission: votify.admin
    aliases: [vadmin, va]

permissions:
  votify.admin:
    description: Allows access to admin commands for Votify.
    default: op
